apiVersion: v1
kind: Service
metadata:
    name:   welcome
spec:
   selector:
     app:  welcome
   ports:
      -  name :  http
         protocol: TCP
         port: 9600
         targetPort: 9600
      -  name:   https
         protocol: TCP
         port: 443
         targetPort: 8081
       
   type : LoadBalancer